
---

#language #cpp

*exception handling*

---

#### 개요

C++에서 말하는 **예외**의 정의는 다음과 같다.

*프로그램 실행 도중에 발생하는 문제상황 = 프로그램의 논리에 맞기 않는 상황*

따라서 문법적인 에러는 예외의 범주에 포함되지 않는다.

C에서는 보통 if else문을 사용해 분기를 구성함으로서 이러한 예외들을 처리한다. 그러나 이러한 방식은 예외처리를 위한 코드와 프로그램의 흐름을 구성하는 코드를 쉽게 구분하지 못한다는 문제가 있다. C++은 이러한 문제를 해결하기 위해 별도의 예외 처리 매커니즘을 보유하고 있다.

---

#### try, catch, throw

C++에서 예외 처리를 위한 키워드는 아래의 3가지가 있다.

| 키워드 | 기능             |
| ------ | ---------------- |
| try    | 예외를 발견한다. |
| catch  | 예외를 잡는다.   |
| throw  | 예외를 던진다.   |

+ try 블록

try 블록은 예외 발생에 대한 검사의 범위를 지정할 때 사용된다. 즉, try 블록 내에서 예외가 발생하면 이는 C++의 예외처리 매커니즘에 의해서 처리가 된다.

```cpp

try
{
	// 예외발생 예외지역
}

```

+ catch 블록

catch 블록은 try 블록에서 발생한 예외를 처리하는 코드가 담기는 영역으로서, 그 형태가 마치 반환형 없는 함수와 유사하다.

```

catch(/*처리할 예외의 종류 명시*/)
{
	// 예외처리 코드의 삽입
}

```

+ 사실 try와 catch는 하나의 단위이다.
	- 따라서 항상 이어서 등장해야 하며, 중간에 다른 문장이 오면 안된다.

종합적으로, try 블록 내에서 발생하는 예외는 이어서 등장하는 catch 블록에 의해 처리된다.

+ throw

키워드 throw는 예외가 발생했음을 알리는 문장의 구성에 사용된다.

```cpp

throw expn;

```

최종적으로 try, catch, throw는 다음과 같이 동작한다.

1. throw에 의해서 '예외 데이터'가 던져진다.
2. '예외 데이터'를 감싸는 try 블록에 의해 감지된다.
3. 이어서 등장하는 catch 블록이 예외를 처리한다.

---

참고자료

[윤성우의 열혈 c++ 프로그래밍](https://product.kyobobook.co.kr/detail/S000001589147)

---